version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: wedding-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wedding-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wedding-app
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - wedding-net

volumes:
  mariadb_data:

networks:
  wedding-net:
    driver: bridge
